theme: jekyll-theme-minimal
title: IWPT 2025
url: "https://www.sigparse.org/iwpt2025"
baseurl: ""
description: >
  IWPT 2025: The 18th International Conference on Parsing Technologies
  
include:
  - _pages
  
sass:
  sass_dir: _sass
